;;; lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from setup-editor.el

(register-definition-prefixes "setup-editor" '("my/harpoon-"))


;;; Generated autoloads from setup-evil.el

(register-definition-prefixes "setup-evil" '("my/window-swap-next"))


;;; Generated autoloads from setup-ui.el

(register-definition-prefixes "setup-ui" '("my/configure-font"))

;;; End of scraped data

(provide 'lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lisp-autoloads.el ends here
